name: WorkBench
version: 1.0.0
author: Shynixn
website: https://www.spigotmc.org/members/shynixn.63455/
main: com.github.shynixn.workbench.bukkit.testsuite.WorkBenchTestSuitePlugin
commands:
  fate:
    description: Fate command.
    useage: /<command>
    permission: fate.admin.command
    permission-message: You don't have permission.